environment:
    MSYSTEM: MSYS
    PATH: C:\msys64\mingw32\bin;C:\msys64\usr\bin;C:\Windows\System32;C:\Windows;%PATH%
    QMAKESPEC: win32-g++

platform:
  - x86

configuration:
  - Release

install:
    - pacman --noconfirm -Sy
    - pacman --noconfirm --needed -S pacman-mirrors
    - pacman --noconfirm -Sy
    - pacman --noconfirm --needed -S mingw32/mingw-w64-i686-qt5 mingw32/mingw-w64-i686-libmad mingw32/mingw-w64-i686-libsndfile mingw32/mingw-w64-i686-flac mingw32/mingw-w64-i686-fftw

build_script:
    - ps: >-
        bash -c @"
          set -e
          # stdin seems to be invalid on appveyor, so set it to null
          exec 0</dev/null 2>&1
          export
          gcc -v
          # disable the test units, since we won't run them
          sed -i -e 's/  SUBDIRS += test/#SUBDIRS += test/g' engine/engine.pro
          sed -i -e 's/SUBDIRS += test/#SUBDIRS += test/g' ui/ui.pro
          qmake FORCECONFIG=release
          make -j4
          make install
        "@


