environment:
    MSYSTEM: MSYS
    PATH: C:\msys64\mingw32\bin;C:\msys64\usr\bin;C:\Windows\System32;C:\Windows;%PATH%
    QMAKESPEC: win32-g++

platform:
  - x86

configuration:
  - Release

install:
    #- pacman --noconfirm -Sy
    #- pacman --noconfirm --needed -S pacman-mirrors
    #- pacman --noconfirm -Sy
    - pacman --noconfirm --needed -S unzip mingw32/mingw-w64-i686-qt5 mingw32/mingw-w64-i686-libmad mingw32/mingw-w64-i686-libsndfile mingw32/mingw-w64-i686-flac mingw32/mingw-w64-i686-fftw

build_script:
    - ps: >-
        bash -c @"
          set -e
          # stdin seems to be invalid on appveyor, so set it to null
          exec 0</dev/null 2>&1
          export
          gcc -v
          # get and prepare the D2XX SDK
          mkdir -p /c/Qt/CDM21200
          wget http://www.ftdichip.com/Drivers/CDM/CDM%20v2.12.16%20WHQL%20Certified.zip -O /c/Qt/CDM21200/cdm.zip
          cd /c/Qt/CDM21200
          unzip cdm.zip
          cd i386
          gendef.exe - ftd2xx.dll > ftd2xx.def
          dlltool -k --input-def ftd2xx.def --dllname ftd2xx.dll --output-lib libftd2xx.a
          cd /c/projects/qlcplus
          # disable the test units, since we won't run them
          sed -i -e 's/  SUBDIRS += test/#SUBDIRS += test/g' engine/engine.pro
          sed -i -e 's/SUBDIRS += test/#SUBDIRS += test/g' ui/ui.pro
          sed -i -e 's/ SUBDIRS              += velleman/#SUBDIRS += velleman/g' plugins/plugins.pro
          qmake FORCECONFIG=release
          make -j4
          make install
        "@


